// Generated by Wrangler on Wed Sep 11 2024 16:36:13 GMT+0630 (Myanmar Time)
// by running `wrangler types`

interface Env {
	TLDRAW: KVNamespace;
	R2_ASSETS_BUCKET_PATH: "https://pub-4d09e2dfecbf4a4ab7d5b29af22c4bba.r2.dev";
	SESSION_SECRET: string;
	CONTENT_BUCKET: R2Bucket;
	ASSETS_BUCKET: R2Bucket;
	DB: D1Database;
}
